name: deploy

on:
  push:
    branches: [source]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: source

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: build
      run: |
        rm -f .yarnclean
        yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
        rm -rf ./public
        yarn run hexo clean
        yarn run hexo generate

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: public
        ssh-key: ${{ secrets.SSH_PRIVATE }}